package Interfaz;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

 public class InterfazServiciosMecanicos extends javax.swing.JFrame {

    /**
     * Creates new form InterfazServicioTaller
     */
    public InterfazServiciosMecanicos() {
        initComponents();
        validacionOperario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInformacionCliente = new java.awt.Label();
        labelTituloVentana1 = new java.awt.Label();
        labelCedulaCliente = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        botonBuscarCliente = new javax.swing.JButton();
        labelIngresarCedula = new java.awt.Label();
        labelCedulaCliente1 = new javax.swing.JLabel();
        labelCedulaCliente2 = new javax.swing.JLabel();
        txtCedulaCliente1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelNombreOperario = new javax.swing.JLabel();
        list2 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelInformacionCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelInformacionCliente.setText("Información Cliente");

        labelTituloVentana1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTituloVentana1.setText("Servicios Mecánicos  ");

        labelCedulaCliente.setText("Cédula Cliente");

        botonBuscarCliente.setText("Buscar Cliente");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });

        labelIngresarCedula.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelIngresarCedula.setText("Ingrese cédula del cliente");

        labelCedulaCliente1.setText("Nombre Cliente: ");

        labelCedulaCliente2.setText("Placas Vehículo(s):");

        jLabel1.setText("Operario: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCedulaCliente)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(botonBuscarCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(labelIngresarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCedulaCliente1)
                            .addComponent(labelCedulaCliente2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedulaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(labelNombreOperario))
                            .addComponent(labelInformacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(338, 338, 338)
                    .addComponent(labelTituloVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(379, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelNombreOperario))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelIngresarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInformacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCedulaCliente)
                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCedulaCliente1)
                    .addComponent(txtCedulaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCedulaCliente2)
                            .addComponent(botonBuscarCliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(labelTituloVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(541, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
        String cedulaCliente = txtCedulaCliente.getText().trim();
        
         try {
            // Establecer conexión a la base de datos
            Connection conexion = conectar();
            
            // Consulta SQL para consultar el cliente y los vehiculos asociados
            String consultaCliente = "SELECT nombre FROM clientes where cedula = (?)";
            
            // Preparar la declaracion SQL
            PreparedStatement declaracionCliente = conexion.prepareStatement(consultaCliente);
            declaracionCliente.setString(1, cedulaCliente);
            
            // Ejecutar la consulta y obtener el resultado
            ResultSet resultado = declaracionCliente.executeQuery();
            
            
            
            
            
         } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, "Error al conectar la base de datos " + e.getMessage());
        }
        
    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    private void validacionOperario(){       
        try {
            String id_Empleado = JOptionPane.showInputDialog("Ingrese su ID de Empleado");
            
            // Establecer conexión a la base de datos
            Connection conexion = conectar();
            
            // Consulta SQL para insertar la transaccion en la tabla de "registromantenimiento"
            String consulta = "SELECT nombre FROM operarios WHERE idEmpleado = (?)";

            // Preparar la declaracion SQL
            PreparedStatement declaracion = conexion.prepareStatement(consulta);
            declaracion.setString(1, id_Empleado);
            
            // Ejecutar la consulta y obtener el resultado
            ResultSet resultado = declaracion.executeQuery();   
            
            while(true){ 
                if (!resultado.isBeforeFirst()){ 
                    JOptionPane.showMessageDialog(null, "[!] El ID de Empleado no se encuentra registrado o no es válido");
                    

                } else {            
                    //Imprimir los resultados en la tabla
                    while (resultado.next()) {
                        String nombre = resultado.getString("nombre");
                        labelNombreOperario.setText(nombre);
                    } 
                    break;
                }
                id_Empleado = JOptionPane.showInputDialog("Ingrese su ID de Empleado");
                declaracion.setString(1, id_Empleado);
                resultado = declaracion.executeQuery();   
            }       
       } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al conectar la base de datos: " + e.getMessage());    
       }
    }
    
    public static Connection conectar() throws SQLException {
        // Datos de conexión a la base de datos
        String url = "jdbc:mysql://localhost:3306/taller";
        String usuario = "root";
        String contrasena = "root";

        // Establecer la conexión y retornarla
        return DriverManager.getConnection(url, usuario, contrasena);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazServiciosMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazServiciosMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazServiciosMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazServiciosMecanicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazServiciosMecanicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCedulaCliente;
    private javax.swing.JLabel labelCedulaCliente1;
    private javax.swing.JLabel labelCedulaCliente2;
    private java.awt.Label labelInformacionCliente;
    private java.awt.Label labelIngresarCedula;
    private javax.swing.JLabel labelNombreOperario;
    private java.awt.Label labelTituloVentana1;
    private java.awt.List list2;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCedulaCliente1;
    // End of variables declaration//GEN-END:variables
}
