/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Taller.ConectarDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sams2
 */
public class SubInterfazReporteOperarios extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form SubInterfazReporteOperarios
     */
    public SubInterfazReporteOperarios() {
        initComponents();
        setLocationRelativeTo(null);
         //se crea nuevo modelo de tabla
        modeloTabla = new DefaultTableModel();
        //se asigna el modelo de tabla al jTable
        jTable1.setModel(modeloTabla);
         //se establece las columnas de la tabla
         String[] columnasTabla = {"ID operario", "Nombre", "Telefono", "Direccion", "Correo electronico", "Salario", "Fecha contratacion"};
            modeloTabla.setColumnIdentifiers(columnasTabla);
        //se llama al metodo para listar operarios
        listarOperarios();
    }

    public void listarOperarios() {
        try {
            // Establecer conexion a la base de datos
            ConectarDB connect = new ConectarDB();
            Connection conexion = connect.conectarDB();

            //Consulta SQL para seleccionar todos los registros de los productos
            String consulta = "SELECT id_operario,nombre, telefono, direccion, correoElectronico, salario, fechaContratacion FROM operarios";

            //Preparar la declaracion SQL
            PreparedStatement declaracion = conexion.prepareStatement(consulta);

            // Ejecutar la consulta y obtener el resultado
            ResultSet resultado = declaracion.executeQuery();

            //se establece las columnas de la tabla
            String[] columnasTabla = {"ID operario", "Nombre", "Telefono", "Direccion", "Correo electronico", "Salario", "Fecha contratacion"};
            modeloTabla.setColumnIdentifiers(columnasTabla);
            //Imprimir los resultados en la tabla
            while (resultado.next()) {
                //obtener los datos 
                String id_Operario = resultado.getString("id_operario");
                String nombre = resultado.getString("nombre");
                String telefono = resultado.getString("telefono");
                String direccion = resultado.getString("direccion");
                String correoElectronico = resultado.getString("correoElectronico");
                double salario = resultado.getDouble("salario");
                String fechaContratacion = resultado.getString("fechaContratacion");
                //Creamos un array tipo objeto con los resultados de la consulta
                Object[] resultadoConsulta = {id_Operario, nombre, telefono, direccion, correoElectronico, salario, fechaContratacion};

                //se agrega fila con los datos
                modeloTabla.addRow(new Object[]{"ID Operario", "Nombre", "Telefono", "Direccion", "Correo electronico", "Salario", "Fecha contratacion"});

            }
            // Cerrar la conexión
            conexion.close();
            resultado.close();
            declaracion.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al listar los productos de la base de datos - Error: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBOperarioBuscar = new javax.swing.JButton();
        txtFiltroOperario = new javax.swing.JTextField();
        labelTituloVentana = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Ingrese la fecha de contratacion");

        jBOperarioBuscar.setText("Buscar");
        jBOperarioBuscar.setToolTipText("");
        jBOperarioBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOperarioBuscarActionPerformed(evt);
            }
        });

        txtFiltroOperario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroOperarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jBOperarioBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFiltroOperario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFiltroOperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBOperarioBuscar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        labelTituloVentana.setAlignment(java.awt.Label.CENTER);
        labelTituloVentana.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTituloVentana.setText("Reporte Operarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(labelTituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(labelTituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBOperarioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOperarioBuscarActionPerformed
        // TODO add your handling code here:
        //se optiene la fecha de contratacion que ingresa el usuario
        String fechaContratacion = txtFiltroOperario.getText();
        //se consulta sql para seleccionar los datos
        String consulta = "SELECT id_operario, nombre, telefono, direccion, correoElectronico, salario, fechaContratacion FROM operarios WHERE fechaContratacion=?";

        //se establece conexion a la base de datos
        try {
            // Establecer conexion a la base de datos
            ConectarDB connect = new ConectarDB();
            Connection conexion = connect.conectarDB();
            PreparedStatement statement = conexion.prepareStatement(consulta);
            //Se establece el parametro de fecha en la consulta
            statement.setString(1, fechaContratacion);
            //se ejecuta la consulta y se obtiene el resultado
            ResultSet resultado = statement.executeQuery();
            //se limpia la tabla para agregar los nuevos datos
            modeloTabla.setRowCount(0);
            //llena la tabla segun la consulta
            while (resultado.next()) {
                //se optienen los datos
                String id_operario = resultado.getString("id_operario");
                String nombre = resultado.getString("nombre");
                String telefono = resultado.getString("telefono");
                String direccion = resultado.getString("direccion");
                String correo = resultado.getString("correoElectronico");
                double salario = resultado.getDouble("salario");
                String fecha = resultado.getString("fechaContratacion");
                //se agrega fila a tabla con los datos
                modeloTabla.addRow(new Object[]{id_operario, nombre, telefono, direccion, correo, salario, fecha});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al listar los productos de la base de datos - Error: " + e.getMessage());
        }

    }//GEN-LAST:event_jBOperarioBuscarActionPerformed

    private void txtFiltroOperarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroOperarioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFiltroOperarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteOperarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubInterfazReporteOperarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOperarioBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label labelTituloVentana;
    private javax.swing.JTextField txtFiltroOperario;
    // End of variables declaration//GEN-END:variables
}
