package Interfaz;

import Gestores.GestorReportes;
import Taller.ConectarDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SubInterfazReporteClientesYVehiculos extends javax.swing.JFrame {
    private DefaultTableModel clientesDefaultModel;
    private DefaultTableModel vehiculosDefaultModel;

    /**
     * Creates new form SubInterfazReporteClientesYVehiculos
     */
    public SubInterfazReporteClientesYVehiculos() {
        initComponents();
        setLocationRelativeTo(null);
        clientesDefaultModel = (DefaultTableModel) jTableCliente.getModel();//Obtiene modelo de tabla clientes
        vehiculosDefaultModel = (DefaultTableModel) jTableVehiculos.getModel();
        listarClientesYVehiculos();//llama al metodo para listar clientes
    }
    
    public void listarClientesYVehiculos() {
        try {
            //conexion a la base de datos
            ConectarDB connect = new ConectarDB();
            //obtiene la conexion
            Connection conexion = connect.conectarDB();

            //Consulta SQL para seleccionar todos los registros de los productos
            String consulta = "SELECT clientes.cedula,clientes.nombre,vehiculos.placa,vehiculos.marca FROM clientes JOIN vehiculos ON clientes.cedula = vehiculos.cedula";

            //Preparar la declaracion SQL
            PreparedStatement declaracion = conexion.prepareStatement(consulta);

            // Ejecutar la consulta y obtener el resultado
            ResultSet resultado = declaracion.executeQuery();

            //Imprimir los resultados en la tabla
            while (resultado.next()) {
                String ced_cliente = resultado.getString("cedula");
                String nombre_cliente = resultado.getString("nombre");

                clientesDefaultModel.addRow(new Object[]{ced_cliente, nombre_cliente});

            }
            // Cerrar la conexión
            conexion.close();
            resultado.close();
            declaracion.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    /**
     * Creates new form InterfazReporteVehiculos
     */
    private String obtenerCedulaClienteSeleccionado() {
        //se obtienw el indice de la fila seleccionada en la tabla clientes
        int filaSeleccionada = jTableCliente.getSelectedRow();
        //se verificaque se seleccionara una fila
        if (filaSeleccionada != -1) {
            //se obtiene la cedula correspondiente a la fila seleccionada
            return (String) jTableCliente.getValueAt(filaSeleccionada, 0);
        } else {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVehiculos = new javax.swing.JTable();
        jBBuscarVehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(jTableCliente);

        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca"
            }
        ));
        jScrollPane2.setViewportView(jTableVehiculos);

        jBBuscarVehiculo.setText("Buscar vehiculo");
        jBBuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jBBuscarVehiculo)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jBBuscarVehiculo)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarVehiculoActionPerformed
        // TODO add your handling code here:
        //se obtiene la cedula del cliente seleccionada
        String cedulaClienteSeleccionado = obtenerCedulaClienteSeleccionado();

        //se verifica que se seleccione un cliente
        if (cedulaClienteSeleccionado != null) {
            //se crea instancia del gestorReportes
            GestorReportes reporte = new GestorReportes();

            //segun la cedula seleccionada se obtiene los vehiculos relacionados
            reporte.reporteDetalladoVehiculos();

            //se establece modelo de la tabla vehiculos con los vehiculos obtenidos
            jTableVehiculos.setModel(reporte.getVehiculoDetalladoVehiculos());

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente");

        }

    }//GEN-LAST:event_jBBuscarVehiculoActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteClientesYVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteClientesYVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteClientesYVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteClientesYVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubInterfazReporteClientesYVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarVehiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableVehiculos;
    // End of variables declaration//GEN-END:variables
}
