/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Gestores.GestorAdministracionProductos;

/**
 *
 * @author sams2
 */
public class SubInterfazReporteVentaProductos extends javax.swing.JFrame {

    /**
     * Creates new form SubInterfazReporteVentaProductos
     */
    public SubInterfazReporteVentaProductos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloVentana = new java.awt.Label();
        labelProductosVendidos = new javax.swing.JLabel();
        botonListarVentas = new javax.swing.JButton();
        labelTotalVentas = new javax.swing.JLabel();
        labelTotalVentas1 = new javax.swing.JLabel();
        labelTotalVentasMostrar = new javax.swing.JLabel();
        labelTotalMontoMostrar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        labelTotalVentasEfectivo = new javax.swing.JLabel();
        labelTotalVentasTarjeta = new javax.swing.JLabel();
        labelTotalVentasTarjetaMostrar = new javax.swing.JLabel();
        labelTotalVentasEfectivoMostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTituloVentana.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTituloVentana.setText("Reporte Ventas de Productos");

        labelProductosVendidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelProductosVendidos.setText("Lista General de Ventas");

        botonListarVentas.setText("Listar Ventas");
        botonListarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarVentasActionPerformed(evt);
            }
        });

        labelTotalVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTotalVentas.setText("Total Número Ventas: ");

        labelTotalVentas1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTotalVentas1.setText("Total Monto Ventas: ");

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N. Factura", "Cédula", "Total Pagado", "Tipo Pago"
            }
        ));
        jScrollPane2.setViewportView(tablaVentas);

        labelTotalVentasEfectivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTotalVentasEfectivo.setText("Total Ventas Efectivo:");

        labelTotalVentasTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTotalVentasTarjeta.setText("Total Ventas Tarjeta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(labelTituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotalVentas)
                            .addComponent(labelTotalVentas1)
                            .addComponent(labelTotalVentasEfectivo)
                            .addComponent(labelTotalVentasTarjeta))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotalVentasTarjetaMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotalMontoMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotalVentasMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotalVentasEfectivoMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(botonListarVentas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(labelProductosVendidos)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(labelProductosVendidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotalVentas)
                            .addComponent(labelTotalVentasMostrar))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotalVentas1)
                            .addComponent(labelTotalMontoMostrar))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotalVentasEfectivo)
                            .addComponent(labelTotalVentasEfectivoMostrar))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotalVentasTarjeta)
                            .addComponent(labelTotalVentasTarjetaMostrar)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonListarVentas)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarVentasActionPerformed
        GestorAdministracionProductos reporte = new GestorAdministracionProductos();
        reporte.listarVentas();
        tablaVentas.setModel(reporte.getVentasProductos());
        
        //Adicional mostramos los valores de los labels
        labelTotalVentasMostrar.setText(String.valueOf(reporte.getTotalNumeroVentas()));
        labelTotalMontoMostrar.setText(String.valueOf(reporte.getTotalMontoVentas()));
        labelTotalVentasEfectivoMostrar.setText(String.valueOf(reporte.getTotalVentasEfectivo()));
        labelTotalVentasTarjetaMostrar.setText(String.valueOf(reporte.getTotalVentasTarjeta()));
    }//GEN-LAST:event_botonListarVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteVentaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteVentaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteVentaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteVentaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubInterfazReporteVentaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonListarVentas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelProductosVendidos;
    private java.awt.Label labelTituloVentana;
    private javax.swing.JLabel labelTotalMontoMostrar;
    private javax.swing.JLabel labelTotalVentas;
    private javax.swing.JLabel labelTotalVentas1;
    private javax.swing.JLabel labelTotalVentasEfectivo;
    private javax.swing.JLabel labelTotalVentasEfectivoMostrar;
    private javax.swing.JLabel labelTotalVentasMostrar;
    private javax.swing.JLabel labelTotalVentasTarjeta;
    private javax.swing.JLabel labelTotalVentasTarjetaMostrar;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
