package Interfaz;

import Taller.ConectarDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SubInterfazReporteClientesYVehiculos extends javax.swing.JFrame {
    private DefaultTableModel clientesDefaultModel;
    /**
     * Creates new form SubInterfazReporteClientesYVehiculos
     */
    public SubInterfazReporteClientesYVehiculos() {
        initComponents();
        setLocationRelativeTo(null);
        clientesDefaultModel = (DefaultTableModel) jTableCliente.getModel();//Obtiene modelo de tabla clientes
        listarClientesYVehiculos();//llama al metodo para listar clientes
    }
    
    public void listarClientesYVehiculos() {
        try {
            ConectarDB connect = new ConectarDB();//conexion a la base de datos
            Connection conexion = connect.conectarDB();//obtiene la conexion

            //Consulta SQL para seleccionar todos los registros de los productos
            String consulta = "SELECT clientes.cedula,clientes.nombre,vehiculos.placa,vehiculos.marca FROM clientes JOIN vehiculos ON clientes.cedula = vehiculos.cedula";

            //Preparar la declaracion SQL
            PreparedStatement declaracion = conexion.prepareStatement(consulta);

            // Ejecutar la consulta y obtener el resultado
            ResultSet resultado = declaracion.executeQuery();

            //Imprimir los resultados en la tabla
            while (resultado.next()) {
                String ced_cliente = resultado.getString("cedula");
                String nombre_cliente = resultado.getString("nombre");

                clientesDefaultModel.addRow(new Object[]{ced_cliente, nombre_cliente});

            }
            // Cerrar la conexión
            conexion.close();
            resultado.close();
            declaracion.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(jTableCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        String cedulaCliente = clientesDefaultModel.getValueAt(jTableCliente.getSelectedRow(), 0).toString();
        //abrir la ventana vehiculos
        SubInterfazReporteVehiculos ventanaVehiculos = new SubInterfazReporteVehiculos(cedulaCliente);
        ventanaVehiculos.setVisible(true);
        this.setVisible(false);
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteClientesYVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteClientesYVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteClientesYVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubInterfazReporteClientesYVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubInterfazReporteClientesYVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    // End of variables declaration//GEN-END:variables
}
